// API catalog store + builder.
//
// Orchestrates the discovery pipeline: ask the plugin to enumerate the live API
// surface (introspect_api), run a curated set of safe schema probes
// (probe_schema), decode each error with schema-probe.js, and assemble a
// versioned catalog. Persistence is injected so the assembler stays testable.

import fs from "node:fs";
import { parseValidationError, summarizeShape } from "./schema-probe.js";

// Curated, safe probes. Each entry deliberately calls a validated method with
// an invalid argument so the error reveals its schema. None are destructive
// (the plugin also enforces a denylist).
export const DEFAULT_PROBES = [
  { key: "applyAnimationStyle", on: "node", method: "applyAnimationStyle", invalidArgs: [{}] },
  { key: "applyManualKeyframeTrack.field", on: "node", method: "applyManualKeyframeTrack", invalidArgs: [{ type: "PROPERTY", name: "__invalid__" }, { keyframes: [] }] },
  { key: "setReactionsAsync", on: "node", method: "setReactionsAsync", invalidArgs: [[{ __invalid__: true }]] },
  { key: "createImageAsync", on: "figma", method: "createImageAsync", invalidArgs: [12345] }
];

/**
 * Build the catalog from live discovery. Pure orchestration: I/O is injected.
 * @param {object} deps
 * @param {(cmd:object, timeoutMs?:number)=>Promise<object>} deps.sendToFigma
 * @param {Array} [deps.probes]
 * @returns {Promise<object>} the assembled catalog
 */
export async function buildCatalog({ sendToFigma, probes = DEFAULT_PROBES }) {
  const intro = await sendToFigma({ type: "introspect_api" }, 30_000);
  const introspection = (intro && intro.introspection) || intro || {};

  const schemas = {};
  for (const probe of probes) {
    try {
      const res = await sendToFigma({ type: "probe_schema", spec: probe }, 30_000);
      if (res && res.threw && res.errorString) {
        const parsed = parseValidationError(res.errorString);
        schemas[probe.key] = {
          method: probe.method,
          on: probe.on || "figma",
          ...parsed,
          shape: summarizeShape(parsed)
        };
      } else if (res && res.threw === false) {
        schemas[probe.key] = { method: probe.method, on: probe.on || "figma", note: "did not throw; no schema leaked", returned: res.returned };
      } else if (res && res.ok === false) {
        schemas[probe.key] = { method: probe.method, error: res.error };
      }
    } catch (err) {
      schemas[probe.key] = { method: probe.method, error: err.message };
    }
  }

  return {
    $comment: "Auto-generated by build_api_catalog. Maps the live Figma Plugin API surface + decoded input schemas.",
    source: "local-plugin",
    apiVersion: introspection.apiVersion || null,
    editorType: introspection.editorType || null,
    capturedAt: new Date().toISOString(),
    globalKeys: introspection.globalKeys || [],
    nodeTypes: introspection.nodeTypes || {},
    schemas
  };
}

/**
 * Compare two catalogs and report added/removed global keys and node types.
 * @param {object|null} prev
 * @param {object} next
 */
export function diffCatalogs(prev, next) {
  const prevGlobals = new Set((prev && prev.globalKeys ? prev.globalKeys : []).map((g) => (typeof g === "string" ? g : g.name)));
  const nextGlobals = (next.globalKeys || []).map((g) => (typeof g === "string" ? g : g.name));
  const addedGlobals = nextGlobals.filter((n) => !prevGlobals.has(n));
  const removedGlobals = [...prevGlobals].filter((p) => !nextGlobals.includes(p));

  const prevTypes = Object.keys((prev && prev.nodeTypes) || {});
  const nextTypes = Object.keys(next.nodeTypes || {});
  const addedNodeTypes = nextTypes.filter((t) => !prevTypes.includes(t));
  const removedNodeTypes = prevTypes.filter((t) => !nextTypes.includes(t));

  return { addedGlobals, removedGlobals, addedNodeTypes, removedNodeTypes };
}

/** File-backed catalog persistence. */
export function createApiCatalogStore({ localDataDir, apiCatalogPath }) {
  function read() {
    try {
      return JSON.parse(fs.readFileSync(apiCatalogPath, "utf8"));
    } catch {
      return null;
    }
  }
  function write(catalog) {
    fs.mkdirSync(localDataDir, { recursive: true });
    fs.writeFileSync(apiCatalogPath, JSON.stringify(catalog, null, 2));
    return apiCatalogPath;
  }
  return { apiCatalogPath, read, write };
}
